### ISSUE TITLE
Language server crashed

### ISSUE THREAD

**Issue by marc71** [SkaceKamen/vscode-sqflint#1]
After updating to version 0.5.5 i got the following error:

[...]
Adding bis_fnc_simpleobjectdata 3
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at Socket._writeGeneric (net.js:706:26)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at SQFLint.process (C:\Users\xxx\.vscode\extensions\skacekachna.sqflint-0.5.5\server\sqflint.js:88:21)
    at SQFLint.runLint (C:\Users\xxx\.vscode\extensions\skacekachna.sqflint-0.5.5\server\sqflint.js:23:14)
    at Timeout._onTimeout (C:\Users\xxx\.vscode\extensions\skacekachna.sqflint-0.5.5\server\sqflint.js:110:23)
[Error - 22:20:24] Connection to server got closed. Server will not be restarted.

**Comment by SkaceKamen** [comment]
Does it happen every time you launch the editor?

**Comment by SkaceKamen** [comment]
I'll add exception handler to stop server from crashing, but I don't know if this is just aftermath of another problem.

**Comment by marc71** [comment]
Crashes every time when opening a .sqf file - doesn't crash with no files or other files opened. My other extensions installed: C/C++ 0.9.2, C# 1.5.2, PHP Code Format 1.3.0 - nothing else. And it just crashes the SQF Language Server - VSCode works fine with SQF Systax highlightning. The previous version worked without any error. Anyhow hope you can find & fix it - just brought a few friends to VS Code because of SQFLint and SQF Language... Murphy's law... Keep up the good work, thanks.

**Comment by SkaceKamen** [comment]
And are you sure you have [sqflint](https://github.com/SkaceKamen/sqflint/releases) installed?

Anyway, in next version (expected to release in next week), this'll be hopefully fixed.

**Comment by SkaceKamen** [comment]
So, new version was released. Could you test if the issue persists?

Also I forgot to include one dependency, **Java**. It is required because the parser is written in javacc, whitch currently only outputs to Java.

**Comment by marc71** [comment]
Hey, yes am sure - as I said, the previous version worked w/o flaws. Just updated it - no errors, seems to work fine. Thank you very much, appreciate it!

**Comment by SkaceKamen** [comment]
Good
