### ISSUE TITLE
InvalidPathException on indexing

### ISSUE THREAD

**Issue by Silver0** [SkaceKamen/vscode-sqflint#54]
## Description
So, I just installed this extension and [SQF Language by Armitxes](https://github.com/Armitxes/VSCode_SQF) to try it out. I am trying to edit some stuff in a fork of [A3Wasteland (Stratis)](https://github.com/A3Wasteland/ArmA3_Wasteland.Stratis).

When I open the project in VS Code and the indexing starts I get the following error:
```
Indexing workspace...
SQFLint: Error message Mai 03, 2019 2:01:28 PM cz.zipek.sqflint.SQFLintServer processMessage
SEVERE: Error when parsing c:\Users\Silver\git\ArmA3_Wasteland.Stratis\client\inventory\add.sqf
Mai 03, 2019 2:01:28 PM cz.zipek.sqflint.SQFLintServer processMessage
SEVERE: null
java.nio.file.InvalidPathException: Illegal char <"> at index 10: define.sqf"
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at sun.nio.fs.AbstractPath.resolve(Unknown Source)
	at cz.zipek.sqflint.preprocessor.SQFPreprocessor.process(SQFPreprocessor.java:216)
	at cz.zipek.sqflint.SQFLintServer.parse(SQFLintServer.java:160)
	at cz.zipek.sqflint.SQFLintServer.processMessage(SQFLintServer.java:87)
	at cz.zipek.sqflint.SQFLintServer.start(SQFLintServer.java:63)
	at cz.zipek.sqflint.SQFLint.main(SQFLint.java:157)
```
Further, the indexing progress gets stuck at 17% after this error.

Code inside [add.sqf](https://github.com/A3Wasteland/ArmA3_Wasteland.Stratis/blob/dev/client/inventory/add.sqf) (without comments):
```sqf
#include "define.sqf";
private ["_id", "_qty"];
_id = _this select 0;
_qty = _this select 1;
_abs = false;
if (count _this > 2) then {
	if (_this select 2) then {
		_abs = true;
	};
};
private ["_item", "_current"];
_item = _id call mf_inventory_get;
if (_item isEqualTo objNull) exitWith {};
_current = _item select QTY;
if (_abs) then {
	_item set [QTY, _qty];
} else {
	_item set [QTY, _current + _qty];
};
```

Code inside [define.sqf](https://github.com/A3Wasteland/ArmA3_Wasteland.Stratis/blob/dev/client/inventory/define.sqf) (without comments):
```sqf
#define ID 0
#define QTY 1
#define NAME 2
#define USE 3
#define OBJECT 4
#define ICON 5
#define MAX 6
```
## Steps to Reproduce
1. Fork/Clone [A3Wasteland (Stratis)](https://github.com/A3Wasteland/ArmA3_Wasteland.Stratis) to local 
1. Open project in VS Code
1. Let the indexing start
1. Exception pops up and indexing gets stuck at 17%

**Comment by Wyqer** [comment]
Don't know if it might be connected to this....

We've a similar issue on the old framework of Liberation, where the indexing doesn't even seem to start. Also no errors pop up so far. Every tooltip about own functions/variables or even normal A3 commands/functions only show "loading..." and nothing else.

**Reproduce by:**
* Clone https://github.com/KillahPotatoes/KP-Liberation
* Switch to branch `v0.96.5` (`master` should also give this issue, I guess)
* Open cloned repo at root directory (right click KP-Liberation folder, Open with Code)
* Open any file (example the kp_liberation_config.sqf)
* See no indexing is running
* Hover over any engine command or variable and you won't get any tooltip
