### ISSUE TITLE
SQFLint: Process crashed with code -4058

### ISSUE THREAD

**Issue by iAcolyte** [SkaceKamen/vscode-sqflint#86]
Here's output. The previous version works fine.

```
[03:35:29] [Info] [server] Indexing workspace...
[03:35:30] [Info] [sqflint] Starting background server...
(node:11904) UnhandledPromiseRejectionWarning: Error: write EPIPE
at afterWriteDispatched (internal/stream_base_commons.js:149:25)
at writeGeneric (internal/stream_base_commons.js:140:3)
at Socket._writeGeneric (net.js:776:11)
at Socket._write (net.js:788:8)
at doWrite (_stream_writable.js:435:12)
at writeOrBuffer (_stream_writable.js:419:5)
at Socket.Writable.write (_stream_writable.js:309:11)
at c:\Users\acolyte\.vscode\extensions\skacekachna.sqflint-0.11.0\server\sqflint.js:206:37
at new Promise (<anonymous>)
at SQFLint.parse (c:\Users\acolyte\.vscode\extensions\skacekachna.sqflint-0.11.0\server\sqflint.js:195:16)
(node:11904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[03:35:30] [Info] [sqflint] Background server started
[Error - 03:35:30] [03:35:30] [Error] [sqflint] SQFLint: Process crashed Error: spawn java ENOENT
[Error - 03:35:30] [03:35:30] [Error] [sqflint] SQFLint: Process crashed with code -4058
[03:35:30] [Info] [server] Done module index... Now indexing sqf
[03:35:30] [Info] [server] Parsing a total of sqf 446 files
[03:35:30] [Info] [sqflint] Starting background server...
(node:11904) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:149:25)
    at writeGeneric (internal/stream_base_commons.js:140:3)
    at Socket._writeGeneric (net.js:776:11)
    at Socket._write (net.js:788:8)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Socket.Writable.write (_stream_writable.js:309:11)
    at c:\Users\acolyte\.vscode\extensions\skacekachna.sqflint-0.11.0\server\sqflint.js:206:37
    at new Promise (<anonymous>)
    at SQFLint.parse (c:\Users\acolyte\.vscode\extensions\skacekachna.sqflint-0.11.0\server\sqflint.js:195:16)
(node:11904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[03:35:30] [Info] [sqflint] Background server started
[Error - 03:35:30] [03:35:30] [Error] [sqflint] SQFLint: Process crashed Error: spawn java ENOENT
[Error - 03:35:30] [03:35:30] [Error] [sqflint] SQFLint: Process crashed with code -4058
```

**Comment by Aebian** [comment]
You need to have java to run the plugin. 
Either install the JDK version. 

Or download the OpenJDK version at https://jdk.java.net/15/
Then extract the content of the folder to a location if your choice 

Then do the following:
- Add a variable via control sysdm.cpl  >> Advanced >> Environment Variables
![image](https://user-images.githubusercontent.com/7494018/103161789-407ec780-47e7-11eb-9062-e0bc5457ab63.png)
- Also add the bin folder to your PATH variable
![image](https://user-images.githubusercontent.com/7494018/103161793-673cfe00-47e7-11eb-95c4-6de75f82cc7a.png)

**Comment by SkaceKamen** [comment]
Hopefully, it's like @Aebian says and you're only missing JRE.

I think we should add some manual check for `java` and display an informative message when it's missing. Also maybe add the possibility to define a custom path to JRE, if somebody wants to use different than default one.

**Comment by Aebian** [comment]
@iAcolyte Did the steps provided work out or do you still have the issue?

**Comment by iAcolyte** [comment]
> @iAcolyte Did the steps provided work out or do you still have the issue?

Sorry, didn’t try it yet. I just switched to the old version and use it. I try it and send a comment, how it’s work

**Comment by iAcolyte** [comment]
Tried it.
I set OpenJDK15. Indexing working for me now.
But I still can't get access to DEBUG. It just stopped without any message in OUTPUT console

Besides, sqflint.ignoredVariables with wildcards generic a tons of errors everywhere
"sqflint.ignoredVariables": [
    "ace_*"
],

**Comment by iAcolyte** [comment]
> @iAcolyte Did the steps provided work out or do you still have the issue?

Message above. x)
